name: network-gate
on:
  workflow_dispatch: {}
  pull_request:
    paths: ['**/*']

jobs:
  gate:
    runs-on: ubuntu-latest
    env:
      HOST_PRIMARY: https://arka-squad.app
      HOST_FALLBACK: https://arka-liard.vercel.app
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      ALL_PROXY: ""
      NO_PROXY: "localhost,127.0.0.1,.vercel.app,.vercel.dev,vercel.com,arka-squad.app,www.arka-squad.app,arka-liard.vercel.app"

    steps:
      - uses: actions/checkout@v4

      - name: pick-host
        id: pick
        shell: bash
        run: |
          set -euo pipefail
          code=$(curl -4sS --noproxy '*' -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 15 "$HOST_PRIMARY/api/health" || echo 000)
          if [ "$code" = "200" ]; then
            echo "HOST=$HOST_PRIMARY" >> "$GITHUB_OUTPUT"
            echo "picked=primary"     >> "$GITHUB_OUTPUT"
          else
            echo "HOST=$HOST_FALLBACK" >> "$GITHUB_OUTPUT"
            echo "picked=fallback"     >> "$GITHUB_OUTPUT"
          fi

      - name: log-choice
        shell: bash
        run: |
          echo "Picked host: ${{ steps.pick.outputs.picked }}"
          echo "HOST: ${{ steps.pick.outputs.HOST }}"

      - name: rbac-smokes
        if: ${{ secrets.RBAC_TOKEN_VIEWER != '' && secrets.RBAC_TOKEN_EDITOR != '' && secrets.RBAC_TOKEN_ADMIN != '' }}
        env:
          HOST: ${{ steps.pick.outputs.HOST }}
          TOKEN_VIEWER: ${{ secrets.RBAC_TOKEN_VIEWER }}
          TOKEN_EDITOR: ${{ secrets.RBAC_TOKEN_EDITOR }}
          TOKEN_ADMIN:  ${{ secrets.RBAC_TOKEN_ADMIN }}
        shell: bash
        run: |
          echo "Running smokes on $HOST"
          bash scripts/smoke_agents.sh
