name: network-gate
on:
  workflow_dispatch:
  pull_request:
    paths: ['**/*']
    
jobs:
  gate:
    runs-on: ubuntu-latest
    env:
      HOST_PRIMARY: https://arka-squad.app
      HOST_FALLBACK: https://arka-liard.vercel.app
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      ALL_PROXY: ""
      NO_PROXY: "localhost,127.0.0.1,.vercel.app,.vercel.dev,vercel.com,arka-squad.app,www.arka-squad.app,arka-liard.vercel.app"
    steps:
      - uses: actions/checkout@v4

      - name: debug-proxy
        run: |
          echo "== ENV proxy =="; env | grep -iE 'http_proxy|https_proxy|all_proxy|no_proxy' || true
          echo "== /etc/environment =="; (cat /etc/environment || true) | grep -i proxy || true

      - name: curl primary (arka-team)
        run: |
          set -x
          curl -sv --noproxy '*' "$HOST_PRIMARY/api/health" -o /dev/null || true

      - name: curl fallback (vercel)
        run: |
          set -x
          curl -sv --noproxy '*' "$HOST_FALLBACK/api/health" -o /dev/null || true
