name: network-gate
on:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HOST_PRIMARY: https://arka-squad.app
      HOST_FALLBACK: https://arka-liard.vercel.app
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      ALL_PROXY: ""
      NO_PROXY: "localhost,127.0.0.1,.vercel.app,.vercel.dev,vercel.com,arka-squad.app,www.arka-squad.app,arka-liard.vercel.app"
    steps:
      - uses: actions/checkout@v4

      - name: net-dbg
        run: |
          echo "== proxy env =="; env | grep -iE 'http_proxy|https_proxy|all_proxy|no_proxy' || true
          echo "== resolv =="; cat /etc/resolv.conf || true
          echo "== DNS =="
          getent hosts arka-squad.app || true
          getent hosts arka-liard.vercel.app || true
          echo "== route test =="; which ip && ip route get 1.1.1.1 || true

      - name: curl primary (arka-squad)
        run: |
          set -euxo pipefail
          t0=$(date -Ins)
          code=$(curl -4sS -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 15 "$HOST_PRIMARY/api/health" || echo 000)
          echo "PRIMARY $t0 -> $code"

      - name: curl fallback (vercel)
        run: |
          set -euxo pipefail
          t0=$(date -Ins)
          code=$(curl -4sS -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 15 "$HOST_FALLBACK/api/health" || echo 000)
          echo "FALLBACK $t0 -> $code"
