name: release-cut-demo

on:
  workflow_dispatch:
    inputs:
      host:
        description: "Host to collect evidences from (e.g. https://arka-squad.app)"
        required: true
        type: string
      tag:
        description: "Tag name for the demo cut"
        required: false
        type: string
        default: "v0.1.0-demo"

jobs:
  cut-demo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Collect evidences
        env:
          HOST: ${{ inputs.host }}
          RBAC_TOKEN: ${{ secrets.RBAC_TOKEN_OWNER }}
        run: |
          node scripts/release_evidence.mjs
      - name: Upload evidence artifact
        uses: actions/upload-artifact@v4
        with:
          name: evidence-R3
          path: arka-meta/reports/codex/R3
      - name: Tag release
        env:
          TAG: ${{ inputs.tag }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag -a "$TAG" -m "R3 demo cut (evidences collected)" || true
          git push origin "$TAG" || true

