name: secret-scan
on:
  push:
    paths: ['**/*']
  pull_request:
    paths: ['**/*']
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          version: v8.24.3
          config-path: .github/.gitleaks.toml
          args: --redact --no-banner --exit-code 1
          report-format: json
          report-path: gitleaks.json
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Upload report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks.json

      - name: Summary
        if: always()
        run: |
          echo '### Gitleaks report' >> $GITHUB_STEP_SUMMARY
          if [ -f gitleaks.json ]; then
            echo '```json' >> $GITHUB_STEP_SUMMARY
            cat gitleaks.json >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo 'No leaks detected.' >> $GITHUB_STEP_SUMMARY
          fi

