name: secret-scan
on:
  pull_request:
    paths: ['**/*']

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            detect
            --redact
            --no-banner
            --exit-code 1
            --config .gitleaks.toml
