name: OPS R3 - B1 Smokes
on:
  workflow_dispatch:
  schedule:
    - cron: "15 */6 * * *"

jobs:
  smokes:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        envname: [production, preview]
    environment: ${{ matrix.envname }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Encoding guard (mojibake)
        run: |
          npm ci --ignore-scripts
          npm run ci:encoding:check
      - name: Resolve HOST from environment
        id: host
        run: |
          if [ "${{ matrix.envname }}" = "production" ]; then
            HOST="${{ vars.PROD_HOST }}"
          else
            HOST="${{ vars.PREVIEW_HOST }}"
          fi
          if [ -z "$HOST" ]; then
            echo "ERROR: Missing PROD_HOST/PREVIEW_HOST in GitHub → Settings → Environments → ${{ matrix.envname }} → Variables." >&2
            exit 1
          fi
          echo "host=$HOST" >> "$GITHUB_OUTPUT"

      - name: Generate Trace ID
        id: trace
        run: echo "id=ops-$(date +%s)" >> "$GITHUB_OUTPUT"

      - name: Ensure curl and jq are available
        shell: bash
        run: |
          set -euo pipefail
          echo "Pre-check: curl=$(command -v curl || echo 'N/A'), jq=$(command -v jq || echo 'N/A')"
          if ! command -v curl >/dev/null 2>&1 || ! command -v jq >/dev/null 2>&1; then
            echo "Installing curl + jq..."
            sudo apt-get update -yqq
            sudo apt-get install -yqq curl jq
          fi
          curl --version
          jq --version

      - name: Curl 4 endpoints (expect 200)
        shell: bash
        env:
          SMOKES_AUTH: ${{ secrets.SMOKES_AUTH }}
          VERCEL_BYPASS: ${{ secrets.VERCEL_BYPASS }}
          RBAC_TOKEN_ADMIN:  ${{ secrets.RBAC_TOKEN_ADMIN }}
          RBAC_TOKEN_EDITOR: ${{ secrets.RBAC_TOKEN_EDITOR }}
        run: |
          set -euo pipefail
          BASE="${{ steps.host.outputs.host }}"
          TID="${{ steps.trace.outputs.id }}"
          echo "Trace: $TID | Host: $BASE"

          # Build headers (no secret logging)
          HDR=( -H "X-Trace-Id: $TID" )
          # 1) Priority to SMOKES_AUTH if provided (full 'name: value' line)
          if [[ -n "${SMOKES_AUTH:-}" ]]; then
            HDR+=( -H "${SMOKES_AUTH}" )
          # 2) Else, bearer from RBAC admin token
          elif [[ -n "${RBAC_TOKEN_ADMIN:-}" ]]; then
            HDR+=( -H "Authorization: Bearer ${RBAC_TOKEN_ADMIN}" )
          # 3) Else, bearer from RBAC editor token
          elif [[ -n "${RBAC_TOKEN_EDITOR:-}" ]]; then
            HDR+=( -H "Authorization: Bearer ${RBAC_TOKEN_EDITOR}" )
          fi
          # Preview bypass (if defined)
          if [[ "${{ matrix.envname }}" == "preview" && -n "${VERCEL_BYPASS:-}" ]]; then
            HDR+=( -H "x-vercel-protection-bypass: ${VERCEL_BYPASS}" )
          fi

          # Enable cookie-based bypass in preview (follow redirect to capture Set-Cookie)
          COOKIE_JAR="$RUNNER_TEMP/vercel_cookies.txt"
          CURL_BASE_OPTS=( -sS )
          if [[ "${{ matrix.envname }}" == "preview" && -n "${VERCEL_BYPASS:-}" ]]; then
            HDR+=( -H "x-vercel-set-bypass-cookie: true" )
            CURL_BASE_OPTS+=( -L -c "$COOKIE_JAR" -b "$COOKIE_JAR" )
          fi

          endpoints=( "/api/health" "/api/metrics/kpis" "/api/metrics/runs?page=1&limit=20" )
          if [[ "${AI_STREAM_REQUIRED:-0}" == "1" ]]; then
            endpoints+=( "/api/chat/stream?format=txt" )
          fi

          fail=0
          for ENDPOINT in "${endpoints[@]}"; do
            CODE=$(curl "${CURL_BASE_OPTS[@]}" -o /dev/null -w "%{http_code}" "${HDR[@]}" "$BASE$ENDPOINT")
            echo "$ENDPOINT -> $CODE"
            if [[ "$CODE" != "200" ]]; then
              if [[ "$ENDPOINT" == "/api/chat/stream?format=txt" && "${AI_STREAM_REQUIRED:-0}" != "1" && ( "$CODE" == "404" || "$CODE" == "405" ) ]]; then
                echo "NOTE: $ENDPOINT $CODE tolerated (AI stream optional)."
              else
                fail=1
              fi
            fi
          done

          echo "trace_id=$TID" >> "$GITHUB_ENV"
          test "$fail" -eq 0

      - name: KPIs minimal (visibility)
        shell: bash
        env:
          SMOKES_AUTH: ${{ secrets.SMOKES_AUTH }}
          VERCEL_BYPASS: ${{ secrets.VERCEL_BYPASS }}
          RBAC_TOKEN_ADMIN:  ${{ secrets.RBAC_TOKEN_ADMIN }}
          RBAC_TOKEN_EDITOR: ${{ secrets.RBAC_TOKEN_EDITOR }}
        run: |
          set -euo pipefail
          HDR=( -H "X-Trace-Id: $trace_id" )
          if [[ -n "${SMOKES_AUTH:-}" ]]; then
            HDR+=( -H "${SMOKES_AUTH}" )
          elif [[ -n "${RBAC_TOKEN_ADMIN:-}" ]]; then
            HDR+=( -H "Authorization: Bearer ${RBAC_TOKEN_ADMIN}" )
          elif [[ -n "${RBAC_TOKEN_EDITOR:-}" ]]; then
            HDR+=( -H "Authorization: Bearer ${RBAC_TOKEN_EDITOR}" )
          fi
          if [[ "${{ matrix.envname }}" == "preview" && -n "${VERCEL_BYPASS:-}" ]]; then
            HDR+=( -H "x-vercel-protection-bypass: ${VERCEL_BYPASS}" )
          fi
          # Reuse cookie approach for KPIs call
          COOKIE_JAR="$RUNNER_TEMP/vercel_cookies.txt"
          CURL_BASE_OPTS=( -sS )
          if [[ "${{ matrix.envname }}" == "preview" && -n "${VERCEL_BYPASS:-}" ]]; then
            HDR+=( -H "x-vercel-set-bypass-cookie: true" )
            CURL_BASE_OPTS+=( -L -c "$COOKIE_JAR" -b "$COOKIE_JAR" )
          fi
          curl "${CURL_BASE_OPTS[@]}" "${{ steps.host.outputs.host }}/api/metrics/kpis" "${HDR[@]}" \
            | jq '. | {p95_ttft_ms, p95_rtt_ms, error_rate_percent}'

      - name: AI stream (optional)
        if: ${{ env.AI_STREAM_REQUIRED == '1' }}
        shell: bash
        env:
          RBAC_TOKEN_VIEWER: ${{ secrets.RBAC_TOKEN_VIEWER }}
          CI_PROVIDER_KEY: ${{ secrets.CI_PROVIDER_KEY }}
        run: |
          set -euo pipefail
          BASE="${{ steps.host.outputs.host }}"
          echo "AI stream smoke on $BASE"
          HDRS=( -H "Authorization: Bearer ${RBAC_TOKEN_VIEWER:-}" -H "Accept: text/event-stream" -H "X-Provider: openai" -H "X-Model: gpt-4.1-mini" )
          if [[ -n "${CI_PROVIDER_KEY:-}" ]]; then
            HDRS+=( -H "X-Provider-Key: ${CI_PROVIDER_KEY}" )
          fi
          curl -sS -N -m 20 "${HDRS[@]}" "$BASE/api/chat/stream?agent=AGP&role=viewer" | awk 'NR<=5{print};/"t":"done"/{exit 0}'

      - name: Summary
        if: always()
        run: |
          echo "### ${{ matrix.envname }}: 4x200 | Trace $trace_id" >> "$GITHUB_STEP_SUMMARY"

